# This is a basic workflow to help you get started with Actions

name: IP Workflow

# Controls when the workflow will run
on:
  schedule:
    # every Sunday, get ipupdate data, test and update to kv `proxy`, `proxy_bak`
    - cron: "0 8 * * 0"
    # everyday, get kv `proxy`, test and update the same above, get kv `cfhost`, test and update to kv `cfhost_bak`
    - cron: "0 22 * * *"
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      downloadIP:
        description: "download the updated IP data first before merging the IP data?"
        required: false
        default: "true"
        type: choice
        options:
          - true
          - false

env:
  EVENT_NAME: ${{github.event_name}}
  CF_ACCOUNT_ID: ${{secrets.CF_ACCOUNT_ID}}
  CF_API_TOKEN: ${{secrets.CF_API_TOKEN}}
  CF_NAMESPACE_ID: ${{secrets.CF_NAMESPACE_ID || vars.CF_NAMESPACE_ID}}
  CF_KV_API: https://api.cloudflare.com/client/v4/accounts/${{secrets.CF_ACCOUNT_ID}}/storage/kv/namespaces/${{secrets.CF_NAMESPACE_ID || vars.CF_NAMESPACE_ID}}/values
  AUTH: "Authorization:Bearer ${{secrets.CF_API_TOKEN}}"
  PING_API: https://api.globalping.io/v1/measurements
  PING_LIMIT: 3
  PING_COUNTRY: "HK"
  HTTP_DELAY: 1000
  TRACE_HOST: ${{vars.TRACE_HOST || 'time.cloudflare.com'}}
  TRACE_PATH: /cdn-cgi/trace
  PROXYS: proxys
  PROXYS_BAK: proxys_bak
  PROXYS_UPDATED: proxys_updated
  PROXYS_JSON: src/proxys.json

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-ip:
    if: github.repository_owner == 'GeekSnail'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      shouldDeploy: ${{ steps.put-ip.outputs.shouldDeploy }}
      # data: ${{ steps.put-ip.outputs.data }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: download ip
        if: ${{ contains(github.event.schedule, '* * 0') || inputs.downloadIP == 'true' }}
        run: . .github/common.sh && down_ip

      - name: merge ip
        run: . .github/common.sh && merge_ip

      - name: http test, filter
        run: . .github/common.sh && test_ip

      - id: put-ip
        name: put ip to KV
        run: . .github/common.sh && put_ip

      - name: upload ip file
        uses: actions/upload-artifact@v4
        with:
          name: cfproxys
          path: |
            ip443.txt
            ip80.txt
            ipopenai.txt
            ipx.txt

  deploy:
    if: github.repository_owner == 'GeekSnail'
    needs: update-ip
    uses: ./.github/workflows/update_host.yml
    with:
      shouldDeploy: ${{ needs.update-ip.outputs.shouldDeploy }}
      # proxys: ${{ needs.update-ip.outputs.data }}
    secrets: inherit

  workflow-keepalive:
    if: ${{ github.repository_owner == 'GeekSnail' && github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
